name: Publish Crate

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export-debug "Craborant" ../build/windows/craborant-debug.exe
          godot -v --export-release "Craborant" ../build/windows/craborant-release.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
